name: QA

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  php-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - id: versions
        uses: WyriHaximus/github-action-composer-php-versions-in-range@v1
        with:
          upcomingReleases: true

  unit-tests:
    needs: php-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJson(needs.php-versions.outputs.versions) }}
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: ramsey/composer-install@v3
      - run: composer test:unit

  integration-tests:
    needs: php-versions
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.wp == 'trunk' }}
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJson(needs.php-versions.outputs.versions) }}
        wp: ['latest']
        suite:
          - test:core
          - test:wordpress-seo
          - test:polylang
          - test:autodescription
        include:
          - php: '8.2'
            wp: 'trunk'
            suite: test:core
    name: PHP ${{ matrix.php }} | WP ${{ matrix.wp }} | ${{ matrix.suite }}
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: ramsey/composer-install@v3
      - run: composer ${{ matrix.suite }}
        env:
          WP_VERSION: ${{ matrix.wp }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
      - uses: ramsey/composer-install@v3
      - name: Coverage (core)
        run: php -d pcov.enabled=1 vendor/bin/phpunit --testsuite=unit,integration --coverage-php=build/coverage-core.cov
      - name: Coverage (polylang)
        run: PLUGINS=polylang php -d pcov.enabled=1 vendor/bin/phpunit --testsuite=plugin-integration --coverage-php=build/coverage-polylang.cov
      - name: Coverage (WPML)
        run: PLUGINS=wpml php -d pcov.enabled=1 vendor/bin/phpunit --testsuite=plugin-integration --coverage-php=build/coverage-wpml.cov
      - name: Coverage (wordpress-seo)
        run: PLUGINS=wordpress-seo php -d pcov.enabled=1 vendor/bin/phpunit --testsuite=plugin-integration --coverage-php=build/coverage-wordpress-seo.cov
      - name: Coverage (autodescription)
        run: PLUGINS=autodescription php -d pcov.enabled=1 vendor/bin/phpunit --testsuite=plugin-integration --coverage-php=build/coverage-autodescription.cov
      - name: Merge coverage
        run: |
          composer require --dev phpunit/phpcov --quiet
          vendor/bin/phpcov merge build --clover build/coverage.xml
      - uses: codecov/codecov-action@v5
        with:
          files: build/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  static-analysis:
    uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main

  coding-standards:
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
